In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
south = pd.read_csv("south.csv")

In [ ]:
south.head()

In [ ]:
max_date = south['Data'].max()
min_date = south['Data'].min()

stations = south['station_code'].unique()

print(min_date, max_date)
print(stations)

start_date = '2020-04-30'

In [ ]:
renamed_columns_en = ['date','hour','total precipitation (mm)','pressao atmosferica ao nivel da estacao (mb)','atmospheric pressure max. in the previous hour (mb)','atmospheric pressure min. in the previous hour (mb)','radiation (kj/m2)','air temperature - dry bulb (°c)','dew point temperature (°c)','max. temperature in the previous hour (°c)','min. temperature in the previous hour (°c)','dew temperature max. in the previous hour (°c)','dew temperature min. in the previous hour (°c)','relative humidity max. in the previous hour (%)','relative humidity min. in the previous hour (%)','air relative humidity (%)','wind direction (° (gr))','wind rajada maxima (m/s)','wind speed (m/s)','region','state','station','station_code','latitude','longitude','height']

def process_raw(df):
    """
    ! drop index
    ! rename the columns
    ! combine hour and date columns -> transform to date_time
    ! append columns data from all stations to keep the data granularity
    ! remove not useful columns
    ! return table 
    """
    df.drop(['index'],inplace=True, axis=1)
    df.columns = renamed_columns_en
    df['date_time'] = pd.to_datetime(df['date'] + ' ' +  df['hour'])
    df.drop(['date','hour','pressao atmosferica ao nivel da estacao (mb)','atmospheric pressure max. in the previous hour (mb)','atmospheric pressure min. in the previous hour (mb)','radiation (kj/m2)','air temperature - dry bulb (°c)','dew point temperature (°c)', 'dew temperature max. in the previous hour (°c)','dew temperature min. in the previous hour (°c)','air relative humidity (%)','wind direction (° (gr))','wind rajada maxima (m/s)'], inplace=True, axis=1)

    # station_codes = list(df.station_code.unique())
    # df_models = by_code(df,station_codes[0])
    # if len(station_codes)>1:
    #     for i in station_codes[1:]:
    #         df_temp = by_code(df,i)
    #         df_models = pd.concat([df_models,df_temp],axis=1)
    return df

# def by_code(df, station_code):
#     """
#     ! function that filters the dataframe by station_code and rename the columns by the status code
#     """
#     df_station = None
#     df_station = df[df['station_code'] == station_code]
#     df_station.index = df_station.iloc[:,-1]
#     df_station.drop(['station_code','date_time'],axis=1,inplace=True)
#     df_station.columns = list(map(lambda x: station_code+'_'+x, df_station.columns))
#     return df_station

# def clean_na(df, na_value = -9999):
#     """ 
#     ! replace Na from dataset
#     """
#     df = df.replace(to_replace=na_value,value=np.NaN)
#     df = df[df.iloc[:,1].first_valid_index():]
#     df = df.fillna(method='ffill')
#     return df

def make_dataset(stations, start_date, df):
    """
    ! filter raw data from date and stations code
    ! process data
    ! clean na
    """
    df = df[df['Data'] >= start_date]
    df = df[df['station_code'].apply(lambda x: x in stations)]
    df = process_raw(df)
    # df = clean_na(df)
    return df.reset_index()

In [ ]:
south['relative humidity min. in the previous hour (%)']==-9999]

In [ ]:
south_Clean = make_dataset(stations,'2018-04-03', south)
south_Clean.info()

In [ ]:
south_Clean = make_dataset(stations,'2018-04-03', south)
south_Clean

# the start_date variable I set up produces an empty table

In [ ]:
# south_Clean.to_csv("2018_south.csv")

In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
south = pd.read_csv("2018_south.csv")
south

,Unnamed: 0,index,total precipitation (mm),max. temperature in the previous hour (°c),min. temperature in the previous hour (°c),relative humidity max. in the previous hour (%),relative humidity min. in the previous hour (%),wind speed (m/s),region,state,station,station_code,latitude,longitude,height,date_time
0,0,7576632,0.0,16.8,15.0,96,93,0.1,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-01 23:00:00
1,1,7576633,0.0,15.3,13.9,96,96,0.2,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 00:00:00
2,2,7576634,0.0,14.2,13.2,97,96,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 01:00:00
3,3,7576635,0.0,13.7,12.3,97,97,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 02:00:00
4,4,7576636,0.2,13.1,12.3,97,97,0.0,S,PR,GENERAL CARNEIRO,A875,-26.398611,-51.354444,1018.00,2018-11-02 03:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2509075,2509075,10284883,0.0,21.6,20.7,40,36,4.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 19:00:00
2509076,2509076,10284884,0.0,20.9,20.1,40,36,3.2,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 20:00:00
2509077,2509077,10284885,0.0,20.1,18.4,47,40,2.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 21:00:00
2509078,2509078,10284886,0.0,18.5,17.5,51,46,2.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 22:00:00
2509079,2509079,10284887,0.0,17.5,14.8,62,51,3.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 23:00:00

In [75]:
south[south['date_time']>'2020-01-01']

,Unnamed: 0,index,total precipitation (mm),max. temperature in the previous hour (°c),min. temperature in the previous hour (°c),relative humidity max. in the previous hour (%),relative humidity min. in the previous hour (%),wind speed (m/s),region,state,station,station_code,latitude,longitude,height,date_time
1412664,1412664,9188472,0.0,16.2,15.8,-9999,-9999,1.8,S,SC,ARARANGUA,A867,-28.931353,-49.497920,2.00,2020-09-11 08:00:00
1412665,1412665,9188473,0.0,16.1,15.8,-9999,-9999,2.3,S,SC,ARARANGUA,A867,-28.931353,-49.497920,2.00,2020-09-11 09:00:00
1412666,1412666,9188474,0.0,16.3,16.1,-9999,-9999,1.3,S,SC,ARARANGUA,A867,-28.931353,-49.497920,2.00,2020-09-11 10:00:00
1412667,1412667,9188475,0.0,17.1,16.3,-9999,-9999,3.5,S,SC,ARARANGUA,A867,-28.931353,-49.497920,2.00,2020-09-11 11:00:00
1412668,1412668,9188476,0.0,18.0,17.0,-9999,-9999,3.1,S,SC,ARARANGUA,A867,-28.931353,-49.497920,2.00,2020-09-11 12:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2509075,2509075,10284883,0.0,21.6,20.7,40,36,4.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 19:00:00
2509076,2509076,10284884,0.0,20.9,20.1,40,36,3.2,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 20:00:00
2509077,2509077,10284885,0.0,20.1,18.4,47,40,2.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 21:00:00
2509078,2509078,10284886,0.0,18.5,17.5,51,46,2.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 22:00:00
2509079,2509079,10284887,0.0,17.5,14.8,62,51,3.1,S,RS,LAGOA VERMELHA,A844,-28.222381,-51.512845,833.83,2021-04-30 23:00:00

In [ ]:
# south.drop(south[south['relative humidity min. in the previous hour (%)']==-9999])


south[south['relative humidity min. in the previous hour (%)']==-9999]

In [ ]:
# Get indexes where name column has value john
indexNames = south[south['relative humidity min. in the previous hour (%)']==-9999].index
# Delete these row indexes from dataFrame
south.drop(indexNames , inplace=True)


index2 = south[south['relative humidity max. in the previous hour (%)']==-9999].index
# Delete these row indexes from dataFrame
south.drop(index2 , inplace=True)
south

In [ ]:
index3 = south[south['min. temperature in the previous hour (°c)']==-9999].index
# Delete these row indexes from dataFrame
south.drop(index3 , inplace=True)

index4 = south[south['max. temperature in the previous hour (°c)'] == -9999].index
# Delete these row indexes from dataFrame
south.drop(index4 , inplace=True)

index5 = south[south['total precipitation (mm)'] == -9999].index
south.drop(index5 , inplace=True)

index6 = south[south['wind speed (m/s)'] == -9999].index
south.drop(index6 , inplace=True)
south

In [ ]:
# Checking the -9999 columns were removed
# south[south['max. temperature in the previous hour (°c)'] == -9999]
# south[south['max. temperature in the previous hour (°c)'] == -9999]
# south[south['total precipitation (mm)'] == -9999]
# south[south['wind speed (m/s)'] == -9999]
# south[south['relative humidity min. in the previous hour (%)']==-9999]
south[south['relative humidity max. in the previous hour (%)']==-9999]

In [ ]:
south_2020 = south[south['date_time']>'2020-01-01']

In [ ]:
# Created a new csv from 2020 onward 
# south_2020.to_csv("south2020_onward.csv")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
south2020_onward = pd.read_csv("south2020_onward.csv")
south2020_onward